name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate: false
          activate-environment: femmct-fenicsx
          environment-file: environment.yml
          channels: conda-forge
          conda-remove-defaults: true

      - name: Install package
        run: |
          pip install -e .
      
      - name: Lint with Ruff
        run: |
          ruff check src examples tests --output-format=github --exit-non-zero-on-fix

      - name: Test with Pytest
        run: |
          pytest -v --maxfail=1 --disable-warnings -m "not slow" tests